 image:
   name: hashicorp/terraform:light
   entrypoint:
     - '/usr/bin/env'
     - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

 stages:
   - build
   - deploy
   - destroy

 before_script:
   - mkdir -p ~/.ssh && chmod 700 ~/.ssh
   - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
   - chmod 600 ~/.ssh/id_rsa
   - eval $(ssh-agent -s)
   - terraform --version
   - terraform init

 build:
   stage: build
   script:
     - terraform validate
     - terraform plan

 deploy:
   stage: deploy
   when: manual
   script:
     - terraform apply -auto-approve=true
     - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
     - BASTION_IP=$(terraform output -json bastion_eip | awk -F'[(")]' '{print $2}')
     - cat $BASTION_IP
     - ssh -T -o "StrictHostKeyChecking no" -l ubuntu $BASTION_IP "sudo DEBIAN_FRONTEND=noninteractive apt -y update"
     - ssh -T -o "StrictHostKeyChecking no" -l ubuntu $BASTION_IP "sudo DEBIAN_FRONTEND=noninteractive apt -y install unzip"
     - ssh -T -o "StrictHostKeyChecking no" -l ubuntu $BASTION_IP "git clone https://gitlab.com/itsmeoz/terraform-eks-cluster-deployment.git"
     - ssh -T -o "StrictHostKeyChecking no" -l ubuntu $BASTION_IP "cd terraform-eks-cluster-deployment && kubectl deploy -f simple-app.yaml"
     - ssh -T -o "StrictHostKeyChecking no" -l ubuntu $BASTION_IP "curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"

 destroy:
   stage: destroy
   script:
     - terraform destroy -force -auto-approve
   when: manual
