datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server:80
      access: proxy
      isDefault: true
      
    - name: Loki
      type: Loki
      url: http://loki:3100
      isDefault: true      

grafana:
  enabled: true
  defaultDashboardsEnabled: true
  adminPassword: wizardneon13
  namespaceOverride: ""
  # set pspUseAppArmor to false to fix Grafana pod Init errors
  rbac:
    pspUseAppArmor: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"

  path: /grafana/?(.*)
  hosts:
    - wizardneon.link

grafana.ini:
  server:
    root_url: http://localhost:80/grafana # this host can be localhost

