datasources:
  datasources.yaml:    
    apiVersion: 1
    deleteDatasources:
    - name: Prometheus
      orgId: 1   
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-kube-prometheus-prometheus:9090
      orgId: 1
      access: proxy
      isDefault: true

    - name: loki
      type: loki
      url: http://loki:3100
#      orgId: 1
#      access: proxy
#      isDefault: true       


grafana:
  enabled: true
  defaultDashboardsEnabled: true
  adminPassword: passwd
  namespaceOverride: ""
  # set pspUseAppArmor to false to fix Grafana pod Init errors
  rbac:
    pspUseAppArmor: false

#Persistence:
#  type: pvc
#  enabled: true
#  storageClassName: gp2
#  accessModes:
#    - ReadWriteOnce 
#  finalizers:
#    - kubernetes.io/pvc-protection
#  existingClaim: grafana-volume
#selectorLabels: {}
#subPath: ""    

#extraVolumeMounts: 
#    - name: grafana-volume
#      mountPath: /var/lib/grafana/dashboards
#      readOnly: false


ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"

  path: /grafana/?(.*)
  hosts:
    - wizardneon.link

grafana.ini:
  server:
    root_url: http://localhost:80/grafana # this host can be localhost
 

serverDashboardConfigmaps:
    - custom-dashboards    
serverDashboardFiles: {}    

dashboardProviders: 
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

dashboards: 
    default:
      nginx:
        url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/grafana/dashboards/nginx.json
        token: gittoken

      request-handling-performance:
        url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/grafana/dashboards/request-handling-performance.json
        token: gittoken   

      Kubernetes Deployments:
        gnetId: 5225
        revision: 7
        datasource: Prometheus

      Cluster Monitoring for Kubernetes:
        gnetId: 10000
        revision: 1
        datasource: Prometheus

      Kubernetes Ingress Nginx:
        gnetId: 11875
        revision: 1
        datasource: Prometheus

      Analysis by Pod:
        gnetId: 6879
        revision: 1
        datasource: Prometheus

      K8 Cluster Detail Dashboard:
        gnetId: 10856
        revision: 1
        datasource: Prometheus

      Kubernetes Cluster:
        gnetId: 7249
        revision: 1
        datasource: Prometheus 

      Loki Dashboard quick search:
        gnetId: 12019
        revision: 2
        datasource: loki               
