datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.prometheus.svc.cluster.local
      access: proxy
      isDefault: true

grafana:
  enabled: true
  defaultDashboardsEnabled: true
  adminPassword: wizardneon13
  namespaceOverride: ""
  # set pspUseAppArmor to false to fix Grafana pod Init errors
  rbac:
    pspUseAppArmor: false
grafana.ini:
    server:
      domain: wizardneon.link
      root_url: http://localhost:80/grafana



