apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-grafana
spec:
  rules:
  - host: "wizardneon.link"
    http:
      paths:
      - pathType: Prefix
        path: "/grafana"
        backend:
          service:
            name: grafana
            port:
              number: 80
