apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingresse-grafana
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: wizardneon.link
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 80
        path: /grafana
