apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress-v1
  namespace: grafana
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: wizardneon.link
    http:
      paths:
      - path: /grafana/
        backend:
          serviceName: grafana
          servicePort: 80
