{
 "title": "RPI 1",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource" },
   { "name": "node", "query": "${VAR_NODE}" },
   { "name": "namespace", "query": "${VAR_NAMESPACE}" }
  ]
 },
 "panels": [
  {
   "title": "Pods Running Current",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Pending Total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Failed Total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown Total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Unknown\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded Total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "DeadMansSwitch",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  },
  {
   "title": "Containers Running Current",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Waiting Total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Restarts Total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts{namespace=\"$namespace\"}[30m]))"
    }
   ]
  },
  {
   "title": "Containers Terminated Total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "CPU Cores Req by Containers Current",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\", node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU usage Current",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\"}[5m])) / sum (machine_cpu_cores) * 100"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "description": "The nodes of the cluster",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(kube_node_info) by (node, kubelet_version)"
    }
   ]
  },
  {
   "title": "Number of Nodes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(kube_node_info)" }
   ]
  },
  {
   "title": "Memory Requested By Containers Current",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\", node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory usage Current",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\"}) / sum (machine_memory_bytes) * 100"
    }
   ]
  },
  {
   "title": "Failed Rest Client Request from KubeCTL",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * sum by(instance, job) (rate(rest_client_requests_total{code!~\"2..\"}[5m]))/ sum by(instance, job) (rate(rest_client_requests_total[5m]))"
    }
   ]
  }
 ]
}